apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-demo-dev-taxi-svc
  namespace: demo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgA976j4BjjImMBXMcd5SlO2G+ktZ7++FQDYvn6gXO+rQLMnvG1iF+BfBLaLCnwsLlnAO9PnMHB07Vw02UV/khppDy483jL6nJiIwn7iLwkVrceFK3QMQvwNEj4KdDYuJad4VfHSmyZP9ZfHiZZTlUj5nuJgLNULvn6o3JbsZLk2fHczsmpv3kWfL8cuczS8pVT4SxdGmSLmLK8dnGLk3hmzYDDefYgsoaMoPw1PrNI6iZNTGt1n1VxLQ8joL7nkAtZqc8j/Llxxfs2ti8O7yClFu8apLY2sDGhSLCYYKF499Kk3/uz+KN8g7L6kWmoyJMzamZxEl/e8rDsV8PgVr+/LV8rox8/YuiD9mAM6AQO8vt5a2p0OxnRFnyofxWtyj6no4LRtVTFDbToM9vuKL8WKvpCQVN51xjqsWI9zwvwSceEU437rmUVX70+ALKjlNrEqb51X0SpyUnH266akwwv+xvS9TS5bIcH7TQwops/WozBlM4tMbkC+xLpf1doVn0hgakblu+Od2UsOoq3dN8zaGxdsnItEMqN/u4N+qPbiqTtFtfcAid/2kdhyJBfrBhBYePJDbPiUEfk6eG1EOMRoyOLKaRwwPvY4PL7ciAWYlp6CUk6wX1qpfI9Zlg6RdK6dG+nl+5zQPSvGt3TmIj5ZDSPddwLf9OGNyfvWAIa0a9L+dv6vBjmlnB8vCrQ8wwk+AyOcp3U=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-demo-dev-taxi-svc
      namespace: demo-cicd
    type: Opaque
status: {}
